version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - arangodb
  arangodb:
    image: arangodb
    restart: always
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=changeme
    volumes:
      - arango-data:/var/lib/arangodb3
volumes:
  arango-data:
